-- Seed data for all 28 Indian states with cultural information
INSERT INTO states (name, name_hindi, slug, tagline, description, region, color_primary, color_secondary, color_accent, theme, cultural_story, specialties) VALUES
('Rajasthan', 'राजस्थान', 'rajasthan', 'राजस्थान की शान - Land of Kings and Crafts', 'Land of Kings - Known for majestic palaces, vibrant culture, and desert landscapes', 'North', '#FF6B35', '#F7931E', '#F4A460', 'Royal Desert', 'The royal courts of Rajasthan have been patrons of arts and crafts for centuries. The Maharajas commissioned the finest artisans to create masterpieces that adorned their palaces.', '["Textiles", "Jewelry", "Handicrafts", "Spices"]'),
('Maharashtra', 'महाराष्ट्र', 'maharashtra', 'आर्थिक शक्ति - Economic Powerhouse', 'Economic powerhouse known for Bollywood, business hubs, and rich history', 'West', '#FF9933', '#138808', '#000080', 'Bollywood Heritage', 'Maharashtra diverse culture blends Marathi traditions with cosmopolitan influences, creating vibrant arts and crafts.', '["Cotton Textiles", "Leather Goods", "Electronics", "Automobiles"]'),
('Karnataka', 'कर्नाटक', 'karnataka', 'भारत की सिलिकॉन वैली - Silicon Valley of India', 'Silicon Valley of India with ancient temples and modern IT industry', 'South', '#FF9933', '#000080', '#FFD700', 'Tech Heritage', 'Karnataka beautifully balances ancient temple traditions with modern technology and innovation.', '["Silk Sarees", "Sandalwood Products", "IT Services", "Coffee"]'),
('Tamil Nadu', 'तमिल नाडु', 'tamil-nadu', 'तमिल संस्कृति की धरोहर - Tamil Heritage', 'Land of Temples with rich cultural heritage and classical arts', 'South', '#FF9933', '#FFFFFF', '#DC143C', 'Temple Culture', 'Tamil Nadu ancient temples and classical traditions have fostered an artistic heritage spanning millennia.', '["Bronze Sculptures", "Silk Sarees", "Handicrafts", "Spices"]'),
('Gujarat', 'गुजरात', 'gujarat', 'रंगों का त्योहार - Vibrant Gujarat', 'Vibrant state known for entrepreneurship, textiles, and cultural festivals', 'West', '#FF9933', '#138808', '#C0C0C0', 'Entrepreneurial Spirit', 'Gujarat entrepreneurial spirit and vibrant culture have produced some of India most celebrated textiles and crafts.', '["Textiles", "Chemicals", "Diamonds", "Handicrafts"]'),
('West Bengal', 'पश्चिम बंगाल', 'west-bengal', 'सांस्कृतिक पुनर्जागरण - Cultural Renaissance', 'Cultural capital known for literature, arts, and intellectual heritage', 'East', '#FF6B35', '#FFFFFF', '#FFD700', 'Literary Heritage', 'Bengal cultural renaissance revitalized traditional crafts while embracing modern influences.', '["Textiles", "Jute Products", "Tea", "Handicrafts"]'),
('Uttar Pradesh', 'उत्तर प्रदेश', 'uttar-pradesh', 'भारत का हृदय - Heartland of India', 'Heartland of India with Taj Mahal and rich Mughal heritage', 'North', '#FF9933', '#138808', '#32CD32', 'Mughal Heritage', 'The Mughal influence in Uttar Pradesh created exquisite crafts like Chikankari and pietra dura inlay work.', '["Handicrafts", "Leather Goods", "Textiles", "Brassware"]'),
('Madhya Pradesh', 'मध्य प्रदेश', 'madhya-pradesh', 'भारत का हृदय - Heart of India', 'Heart of India known for wildlife, tribal culture, and ancient monuments', 'Central', '#FF9933', '#138808', '#F4A460', 'Tribal Heritage', 'Madhya Pradesh tribal communities have preserved ancient art forms and craft traditions for generations.', '["Handicrafts", "Textiles", "Tribal Art", "Forest Products"]'),
('Andhra Pradesh', 'आंध्र प्रदेश', 'andhra-pradesh', 'शास्त्रीय विरासत - Classical Heritage', 'Known for spicy cuisine, classical dance forms, and coastal beauty', 'South', '#FF9933', '#138808', '#4169E1', 'Classical Arts', 'Andhra Pradesh rich tradition of classical arts and temple culture has fostered crafts with mythological themes.', '["Textiles", "Leather Products", "Spices", "Pearls"]'),
('Telangana', 'तेलंगाना', 'telangana', 'निज़ामी संस्कृति - Nizami Culture', 'Youngest state known for IT industry, Nizami culture, and pearls', 'South', '#FF1493', '#FF6347', '#FFD700', 'Nizami Culture', 'Telangana blends ancient Nizami heritage with modern IT industry innovations.', '["IT Services", "Pearls", "Textiles", "Pharmaceuticals"]'),
('Kerala', 'केरल', 'kerala', 'स्वर्ग की भूमि - Gods Own Country', 'Gods Own Country known for backwaters, spices, and Ayurveda', 'South', '#006400', '#FFD700', '#8B4513', 'Ayurvedic Heritage', 'Kerala maritime history and spice trade routes brought diverse influences that enriched local crafts.', '["Spices", "Coir Products", "Ayurvedic Products", "Handicrafts"]'),
('Punjab', 'पंजाब', 'punjab', 'पांच नदियों की भूमि - Land of Five Rivers', 'Land of Five Rivers known for agriculture, Sikh culture, and vibrant festivals', 'North', '#FF9933', '#138808', '#FFD700', 'Sikh Culture', 'Punjab rich agricultural heritage and Sikh traditions have fostered crafts that celebrate abundance and spirituality.', '["Agricultural Products", "Textiles", "Sports Goods", "Handicrafts"]'),
('Haryana', 'हरियाणा', 'haryana', 'कृषि की धरती - Agricultural Land', 'Agricultural state known for rich culture and contribution to sports', 'North', '#FF9933', '#138808', '#32CD32', 'Agricultural Heritage', 'Haryana agricultural prosperity has supported traditional crafts and modern sports equipment manufacturing.', '["Agricultural Products", "Textiles", "Automobiles", "Sports Equipment"]'),
('Bihar', 'बिहार', 'bihar', 'आध्यात्मिक विरासत - Spiritual Heritage', 'Ancient land of Buddha and Mahavira with rich spiritual heritage', 'East', '#FF9933', '#138808', '#FFD700', 'Spiritual Heritage', 'Bihar spiritual significance as the birthplace of Buddhism and Jainism has influenced its artistic traditions.', '["Handicrafts", "Textiles", "Madhubani Paintings", "Agricultural Products"]'),
('Odisha', 'ओडिशा', 'odisha', 'मंदिरों की भूमि - Land of Temples', 'Land of Lord Jagannath known for classical dance, temples, and art', 'East', '#FF9933', '#138808', '#DC143C', 'Temple Heritage', 'Odisha ancient temple traditions and classical dance forms have created unique artistic expressions.', '["Handicrafts", "Textiles", "Silver Filigree", "Applique Work"]'),
('Jharkhand', 'झारखंड', 'jharkhand', 'आदिवासी संस्कृति - Tribal Culture', 'Mineral-rich state known for tribal culture and natural beauty', 'East', '#FF9933', '#138808', '#8B4513', 'Tribal Culture', 'Jharkhand tribal communities have preserved ancient craft traditions using natural materials and techniques.', '["Tribal Handicrafts", "Metals", "Silk Products", "Forest Products"]'),
('Chhattisgarh', 'छत्तीसगढ़', 'chhattisgarh', 'आदिवासी कला - Tribal Arts', 'Rice bowl of India known for tribal art and ancient temples', 'Central', '#FF9933', '#138808', '#8B4513', 'Tribal Arts', 'Chhattisgarh tribal communities have maintained ancient artistic traditions for centuries.', '["Handicrafts", "Tribal Art", "Textiles", "Forest Products"]'),
('Assam', 'असम', 'assam', 'चाय की विरासत - Tea Heritage', 'Gateway to Northeast known for tea, silk, and wildlife', 'Northeast', '#FF9933', '#138808', '#8B4513', 'Tea Heritage', 'Assam position as the gateway to Northeast India has created a unique blend of cultural influences in its crafts.', '["Tea", "Silk Products", "Handicrafts", "Bamboo Products"]'),
('Himachal Pradesh', 'हिमाचल प्रदेश', 'himachal-pradesh', 'देव भूमि - Dev Bhoomi', 'Dev Bhoomi known for mountains, spirituality, and apple orchards', 'North', '#4169E1', '#FFFFFF', '#32CD32', 'Mountain Heritage', 'Himachal Pradesh mountain culture and spiritual significance have influenced its traditional crafts and textiles.', '["Woolen Products", "Handicrafts", "Apple Products", "Herbal Products"]'),
('Uttarakhand', 'उत्तराखंड', 'uttarakhand', 'देवों की भूमि - Land of Gods', 'Land of Gods known for spiritual tourism and natural beauty', 'North', '#4169E1', '#FFFFFF', '#32CD32', 'Spiritual Tourism', 'Uttarakhand spiritual significance and natural beauty have created a tradition of religious and nature-inspired crafts.', '["Handicrafts", "Woolen Products", "Herbal Products", "Religious Items"]'),
('Goa', 'गोवा', 'goa', 'पुर्तगाली विरासत - Portuguese Heritage', 'Coastal paradise known for beaches, Portuguese heritage, and vibrant nightlife', 'West', '#FF6347', '#4169E1', '#FFD700', 'Portuguese Heritage', 'Goa Portuguese colonial history has created a unique blend of European and Indian artistic traditions.', '["Cashews", "Feni", "Handicrafts", "Beach Accessories"]'),
('Tripura', 'त्रिपुरा', 'tripura', 'बांस की संस्कृति - Bamboo Culture', 'Princely state known for bamboo products and tribal culture', 'Northeast', '#FF9933', '#138808', '#8B4513', 'Bamboo Culture', 'Tripura abundant bamboo resources have fostered a rich tradition of bamboo crafts and tribal art.', '["Bamboo Products", "Handicrafts", "Textiles", "Tribal Art"]'),
('Meghalaya', 'मेघालय', 'meghalaya', 'मातृसत्तात्मक विरासत - Matrilineal Heritage', 'Abode of Clouds known for living root bridges and matrilineal society', 'Northeast', '#006400', '#FFFFFF', '#8B4513', 'Matrilineal Heritage', 'Meghalaya unique matrilineal society and natural beauty have influenced its traditional crafts and lifestyle.', '["Handicrafts", "Shawls", "Honey", "Organic Products"]'),
('Manipur', 'मणिपुर', 'manipur', 'शास्त्रीय नृत्य - Classical Dance', 'Jewel of India known for classical dance and martial arts', 'Northeast', '#FF9933', '#138808', '#8B4513', 'Classical Dance', 'Manipur rich tradition of classical dance and martial arts has influenced its traditional crafts and textiles.', '["Handicrafts", "Handloom Products", "Pottery", "Bamboo Products"]'),
('Nagaland', 'नागालैंड', 'nagaland', 'त्योहारों की भूमि - Land of Festivals', 'Land of Festivals known for tribal culture and vibrant traditions', 'Northeast', '#FF0000', '#000000', '#FFD700', 'Festival Culture', 'Nagaland vibrant festival culture and tribal traditions have created colorful crafts and textiles.', '["Handicrafts", "Shawls", "Wood Carvings", "Tribal Jewelry"]'),
('Mizoram', 'मिज़ोरम', 'mizoram', 'बांस नृत्य - Bamboo Dance', 'Land of Blue Mountains known for bamboo dance and tribal heritage', 'Northeast', '#006400', '#FFFFFF', '#8B4513', 'Bamboo Dance', 'Mizoram bamboo dance tradition and tribal heritage have influenced its unique crafts and cultural expressions.', '["Bamboo Products", "Handicrafts", "Textiles", "Wood Products"]'),
('Arunachal Pradesh', 'अरुणाचल प्रदेश', 'arunachal-pradesh', 'आदिवासी विविधता - Tribal Diversity', 'Land of Dawn-lit Mountains known for tribal diversity and natural beauty', 'Northeast', '#FF9933', '#138808', '#8B4513', 'Tribal Diversity', 'Arunachal Pradesh diverse tribal communities have preserved unique craft traditions and artistic expressions.', '["Handicrafts", "Handloom Products", "Masks", "Wood Carvings"]'),
('Sikkim', 'सिक्किम', 'sikkim', 'बौद्ध संस्कृति - Buddhist Culture', 'Himalayan state known for organic farming and Buddhist culture', 'Northeast', '#4169E1', '#FFD700', '#FFFFFF', 'Buddhist Culture', 'Sikkim Buddhist culture and organic farming practices have influenced its traditional crafts and lifestyle.', '["Organic Products", "Handicrafts", "Woolen Products", "Herbal Products"]');

-- Sample products for different states
INSERT INTO products (name, description, price, original_price, category, state_id, images, stock_quantity, is_featured, is_active) VALUES
-- Rajasthan products
('Rajasthani Bandhani Saree', 'Traditional tie-dye saree with intricate patterns', 2500.00, 3500.00, 'textiles', (SELECT id FROM states WHERE slug = 'rajasthan'), '["https://example.com/bandhani1.jpg", "https://example.com/bandhani2.jpg"]', 15, true, true),
('Kundan Jewelry Set', 'Exquisite gold-plated jewelry with precious stones', 5000.00, 7000.00, 'jewelry', (SELECT id FROM states WHERE slug = 'rajasthan'), '["https://example.com/kundan1.jpg", "https://example.com/kundan2.jpg"]', 8, true, true),
('Blue Pottery Vase', 'Hand-painted ceramic vase with floral motifs', 1200.00, 1800.00, 'handicrafts', (SELECT id FROM states WHERE slug = 'rajasthan'), '["https://example.com/pottery1.jpg", "https://example.com/pottery2.jpg"]', 20, true, true),

-- Maharashtra products  
('Paithani Silk Saree', 'Luxurious handwoven silk saree with peacock motifs', 15000.00, 20000.00, 'textiles', (SELECT id FROM states WHERE slug = 'maharashtra'), '["https://example.com/paithani1.jpg", "https://example.com/paithani2.jpg"]', 5, true, true),
('Warli Art Painting', 'Traditional tribal art depicting rural life', 800.00, 1200.00, 'art', (SELECT id FROM states WHERE slug = 'maharashtra'), '["https://example.com/warli1.jpg", "https://example.com/warli2.jpg"]', 12, true, true),

-- Gujarat products
('Bandhej Dupatta', 'Colorful tie-dye dupatta with mirror work', 600.00, 900.00, 'textiles', (SELECT id FROM states WHERE slug = 'gujarat'), '["https://example.com/bandhej1.jpg", "https://example.com/bandhej2.jpg"]', 25, true, true),
('Kutch Embroidered Bag', 'Handcrafted bag with intricate embroidery', 1800.00, 2500.00, 'handicrafts', (SELECT id FROM states WHERE slug = 'gujarat'), '["https://example.com/kutch1.jpg", "https://example.com/kutch2.jpg"]', 10, true, true),

-- Kerala products
('Kasavu Saree', 'Traditional Kerala saree with gold border', 3500.00, 4500.00, 'textiles', (SELECT id FROM states WHERE slug = 'kerala'), '["https://example.com/kasavu1.jpg", "https://example.com/kasavu2.jpg"]', 7, true, true),
('Kathakali Mask', 'Colorful handcrafted mask used in classical dance', 2200.00, 3000.00, 'art', (SELECT id FROM states WHERE slug = 'kerala'), '["https://example.com/mask1.jpg", "https://example.com/mask2.jpg"]', 6, true, true);

-- Create sample artisans
INSERT INTO artisans (name, craft, experience, location, state_id, story, rating, products_count, is_verified) VALUES
('Ramesh Kumar', 'Kathputli Puppets', '25 years', 'Udaipur', (SELECT id FROM states WHERE slug = 'rajasthan'), 'Third generation puppet maker preserving ancient traditions', 4.9, 45, true),
('Meera Devi', 'Blue Pottery', '18 years', 'Jaipur', (SELECT id FROM states WHERE slug = 'rajasthan'), 'Master potter creating exquisite blue pottery', 4.8, 32, true),
('Jivya Soma Mashe', 'Warli Painting', '35 years', 'Thane', (SELECT id FROM states WHERE slug = 'maharashtra'), 'Renowned Warli artist preserving tribal art forms', 4.9, 28, true),
('Kiran Patel', 'Kutch Embroidery', '22 years', 'Bhuj', (SELECT id FROM states WHERE slug = 'gujarat'), 'Expert in traditional Kutch embroidery techniques', 4.7, 41, true),
('Lakshmi Nair', 'Coir Weaving', '20 years', 'Alappuzha', (SELECT id FROM states WHERE slug = 'kerala'), 'Skilled coir weaver creating sustainable products', 4.6, 38, true);
